theme: minima
title: Welcome to Skytzopolis 
author: Skytzo1838 Himself...(And people in his head)
email: Skytzo1838@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 From my mind to yours I offer what I find Unique, From PICTURES I have taken to POETRY I have written, Personal EXPERIENCE, STORIES passed down from Generations of my elders.
 Come with me down a Rabbit hole and experience LIFE thru my eyes.

# social links
Facebook_username: https://www.facebook.com/skytzo.polis
github_username:  https://github.com/Skytzopolis
show_excerpts: true # set to false to remove excerpts on the homepage
